package Windows;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 * La ventana que vera el usuario cuando este registrando un sitio de recolección,
 * contiene los metodos: , y los
 * botones, etiquetas y cuadros de texto
 *
 * @author Felipe Tapias
 * @version 1.0
 */
public class register extends javax.swing.JFrame {

    
    public register() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/iconLogo.png"));
        return retValue;
    }

    /**
     * Este metodo obtiene los parametros ingresados por la ventana y los
     * organiza con una estructura de lista.
     *
     * @param codR Codigo del sitio
     * @param nombreR El nombre del sitio
     * @param municipioR El nombre del municipio
     * @param responsableR El nombre del responsable del sitio
     */
    void CrearSitio(String codR, String nombreR, String municipioR, String responsableR) {
        try {
            
        } catch (Exception ex) {
            System.out.println("Ha ocurrido un error" + ex);
        } 
    }

    void vaciarCampos() {
        try {
            Tcod.setText("");
            Tnom.setText("");
            Tmunicipio.setText("");
            Tresponsable.setText("");
        } catch (Exception e) {
            System.out.println("Ha ocurrido un error al vaciar los campos" + e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSession1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Tresponsable = new javax.swing.JTextField();
        Tcod = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Tnom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Tmunicipio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonSession2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonSession3 = new javax.swing.JButton();
        jButtonSession4 = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        jButtonSession1.setBackground(new java.awt.Color(0, 102, 102));
        jButtonSession1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonSession1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSession1.setText("Registrar");
        jButtonSession1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonSession1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSession1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Responsable:");

        Tresponsable.setBackground(new java.awt.Color(0, 102, 102));
        Tresponsable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Tresponsable.setForeground(new java.awt.Color(255, 255, 255));
        Tresponsable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        Tresponsable.setCaretColor(new java.awt.Color(255, 255, 255));
        Tresponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TresponsableActionPerformed(evt);
            }
        });

        Tcod.setBackground(new java.awt.Color(0, 102, 102));
        Tcod.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Tcod.setForeground(new java.awt.Color(255, 255, 255));
        Tcod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        Tcod.setCaretColor(new java.awt.Color(255, 255, 255));
        Tcod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TcodActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Código:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");

        Tnom.setBackground(new java.awt.Color(0, 102, 102));
        Tnom.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Tnom.setForeground(new java.awt.Color(255, 255, 255));
        Tnom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        Tnom.setCaretColor(new java.awt.Color(255, 255, 255));
        Tnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TnomActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Municipio:");

        Tmunicipio.setBackground(new java.awt.Color(0, 102, 102));
        Tmunicipio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Tmunicipio.setForeground(new java.awt.Color(255, 255, 255));
        Tmunicipio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        Tmunicipio.setCaretColor(new java.awt.Color(255, 255, 255));
        Tmunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TmunicipioActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro sitio de recolección");

        jButtonSession2.setBackground(new java.awt.Color(0, 102, 102));
        jButtonSession2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonSession2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSession2.setText("Registrar");
        jButtonSession2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonSession2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSession2ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSession3.setBackground(new java.awt.Color(0, 102, 102));
        jButtonSession3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonSession3.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSession3.setText("Listar");
        jButtonSession3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonSession3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSession3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSession3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 112, 50));

        jButtonSession4.setBackground(new java.awt.Color(0, 102, 102));
        jButtonSession4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonSession4.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSession4.setText("Eliminar");
        jButtonSession4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonSession4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSession4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSession4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 112, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(Tcod, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(Tnom, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(Tmunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tresponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jButtonSession2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addComponent(jLabel6)
                .addGap(11, 11, 11)
                .addComponent(Tcod, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addComponent(Tnom, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addComponent(Tmunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Tresponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButtonSession2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 720, 780));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoDesk.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 832, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TresponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TresponsableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TresponsableActionPerformed

    private void TnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TnomActionPerformed

    private void TmunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TmunicipioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TmunicipioActionPerformed

    private void TcodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TcodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TcodActionPerformed

    private void jButtonSession1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSession1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSession1ActionPerformed

    private void jButtonSession2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSession2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSession2ActionPerformed

    private void jButtonSession3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSession3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSession3ActionPerformed

    private void jButtonSession4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSession4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSession4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Tcod;
    private javax.swing.JTextField Tmunicipio;
    private javax.swing.JTextField Tnom;
    private javax.swing.JTextField Tresponsable;
    private javax.swing.JButton jButtonSession1;
    private javax.swing.JButton jButtonSession2;
    private javax.swing.JButton jButtonSession3;
    private javax.swing.JButton jButtonSession4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
