/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author FelipeTapias
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/iconLogo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextFieldUserLogin1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldUserLogin2 = new javax.swing.JTextField();
        jTextFieldUserLogin3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButtonSession = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldUserLogin = new javax.swing.JTextField();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));

        jTextFieldUserLogin1.setBackground(new java.awt.Color(0, 102, 102));
        jTextFieldUserLogin1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldUserLogin1.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldUserLogin1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jTextFieldUserLogin1.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextFieldUserLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserLogin1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUserLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 300, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Municipio:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));

        jTextFieldUserLogin2.setBackground(new java.awt.Color(0, 102, 102));
        jTextFieldUserLogin2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldUserLogin2.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldUserLogin2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jTextFieldUserLogin2.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextFieldUserLogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserLogin2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUserLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 300, 50));

        jTextFieldUserLogin3.setBackground(new java.awt.Color(0, 102, 102));
        jTextFieldUserLogin3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldUserLogin3.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldUserLogin3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jTextFieldUserLogin3.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextFieldUserLogin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserLogin3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUserLogin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 300, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Código:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        jButtonSession.setBackground(new java.awt.Color(0, 102, 102));
        jButtonSession.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonSession.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSession.setText("Registrar");
        jButtonSession.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSessionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSession, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 660, 300, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro sitio de recolección");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Responsable:");

        jTextFieldUserLogin.setBackground(new java.awt.Color(0, 102, 102));
        jTextFieldUserLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldUserLogin.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldUserLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jTextFieldUserLogin.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextFieldUserLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldUserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(459, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldUserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 500, 720));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoDesk.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 832, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUserLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUserLoginActionPerformed

    private void jTextFieldUserLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserLogin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUserLogin1ActionPerformed

    private void jTextFieldUserLogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserLogin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUserLogin2ActionPerformed

    private void jTextFieldUserLogin3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserLogin3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUserLogin3ActionPerformed

    private void jButtonSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSessionActionPerformed

        

    }//GEN-LAST:event_jButtonSessionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSession;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldUserLogin;
    private javax.swing.JTextField jTextFieldUserLogin1;
    private javax.swing.JTextField jTextFieldUserLogin2;
    private javax.swing.JTextField jTextFieldUserLogin3;
    // End of variables declaration//GEN-END:variables
}
